# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This is a Kconfig fragment which can be used to enable debug-related options
# in the application. See the README for more details.

# compiler
# CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_SIZE_OPTIMIZATIONS=y

# logging
CONFIG_LOG=y
CONFIG_LOG_SPEED=y
CONFIG_LOG_BUFFER_SIZE=8192
CONFIG_LOG_BACKEND_SHOW_COLOR=y
CONFIG_LOG_INFO_COLOR_GREEN=y

# CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_BACKEND_UART_ASYNC=y
CONFIG_LOG_BACKEND_UART_BUFFER_SIZE=64

CONFIG_HW_STACK_PROTECTION=y
CONFIG_STACK_CANARIES=y
# CONFIG_DEBUG_THREAD_INFO=y

# CONFIG_USE_SEGGER_RTT=y
# CONFIG_SEGGER_DEBUGMON=y

CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
# CONFIG_RTT_CONSOLE=y

# shell
CONFIG_SHELL=n
# CONFIG_SHELL_BACKEND_RTT=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_VT100_COLORS=y
CONFIG_SHELL_VT100_COMMANDS=y
# CONFIG_AUDIO_CODEC_SHELL=y

# Log levels
CONFIG_APP_LOG_LEVEL_DBG=y
# CONFIG_REGULATOR_LOG_LEVEL_DBG=y
# CONFIG_DISPLAY_LOG_LEVEL_DBG=y
CONFIG_AUDIO_CODEC_LOG_LEVEL_DBG=y
CONFIG_I2S_LOG_LEVEL_WRN=y

# CONFIG_USBD_MIDI2_LOG_LEVEL_INF=y
# CONFIG_USBD_LOG_LEVEL_WRN=y
# CONFIG_USB_DRIVER_LOG_LEVEL_DBG=n
# CONFIG_UDC_DRIVER_LOG_LEVEL_DBG=n

CONFIG_ASSERT=y
# CONFIG_USE_STM32_ASSERT=y

# CONFIG_UART_LOG_LEVEL_DBG=y
# CONFIG_I2C_SHELL=y
