# CONFIG_IDLE_STACK_SIZE=4096
# CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
# CONFIG_MAIN_STACK_SIZE=8192
CONFIG_SPEED_OPTIMIZATIONS=y
CONFIG_SENSOR=y

CONFIG_SPI=y
CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVERS=y
CONFIG_FILE_SYSTEM=y

CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FS_FATFS_FSTAB_AUTOMOUNT=y
CONFIG_FS_FATFS_MOUNT_MKFS=n
CONFIG_FS_FATFS_MAX_SS=512
CONFIG_FS_FATFS_MIN_SS=512
CONFIG_FS_FATFS_EXFAT=y
CONFIG_FS_FATFS_LBA64=y
CONFIG_FS_FATFS_LFN=y
CONFIG_FS_FATFS_NUM_FILES=104

CONFIG_MAIN_STACK_SIZE=4096

CONFIG_I2S=y
CONFIG_DMA=y
CONFIG_ADC=y

CONFIG_I2S_ESP32_TX_BLOCK_COUNT=8
CONFIG_I2S_ESP32_RX_BLOCK_COUNT=0
CONFIG_I2S_ESP32_ALLOWED_EMPTY_TX_QUEUE_DEFERRAL_TIME_MS=0
CONFIG_ENTROPY_GENERATOR=y
CONFIG_ENTROPY_ESP32_RNG=y

CONFIG_HEAP_MEM_POOL_SIZE=49152
