# CONFIG_IDLE_STACK_SIZE=4096
# CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
# CONFIG_MAIN_STACK_SIZE=8192
CONFIG_SENSOR=y

CONFIG_SPI=y
CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVERS=y
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FS_FATFS_FSTAB_AUTOMOUNT=y
CONFIG_MAIN_STACK_SIZE=4096

CONFIG_I2S=y
CONFIG_DMA=y
