# C3 has no ADC or encoder
CONFIG_ADC=n
CONFIG_SENSOR=n

# UART for STM32 knob controller
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y

# More I2S TX queue depth and tolerate brief empty periods without error recovery
# CONFIG_I2S_ESP32_TX_BLOCK_COUNT=3
CONFIG_I2S_ESP32_ALLOWED_EMPTY_TX_QUEUE_DEFERRAL_TIME_MS=10
